# This is an example config file. Sample command:
# span -r output.dir -b width,height "config/{simulation.mode}/{width}x{height}_{size|%03d}.toml" config.toml

id = 42
size = [5, 10, 200]
width = [640, 800]
height = [480, 600]

[simulation]
	mode = ["normal", "crazy"]

[output]
	dir = "data/{width}x{height}_{size|%03d}_{simulation.mode}{id}.dat"
